---
settings:
  name: ONTAP
  search: ontap,ontap-cli,ontap-automation,ontap-metrocluster,ontap-systems-switches,ontap-technical-reports,ontap-sanhost,asa-r2
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentación de productos de ONTAP
    url: "/index.html"
product-family:
  sidebarlinks:
  - title: Todo
    tags: all
    class: active
  - title: Automatización
    tags: automation
  - title: Datos de empresa
    tags: management
  - title: Migración de datos
    tags: migration
  - title: Protección de datos
    tags: protection
  - title: Sistemas de hardware
    tags: hardware
  tiles:
  - title: ONTAP 9 para sistemas AFF, ASA y FAS
    icon: "./media/icon-onprem.png"
    url: https://docs.netapp.com/us-en/ontap/index.html
    summary: Utilice el software ONTAP para gestionar datos en sistemas FAS all-flash,
      sistemas de cabinas SAN all-flash y cabinas FAS de flash híbrido.
    tags: all, management, protection
  - title: Sistemas AFF, ASA y FAS
    icon: "./media/groups_line.png"
    url: https://docs.netapp.com/us-en/ontap-systems-family/
    summary: Descubra cómo instalar, mantener y actualizar sistemas FAS All-Flash,
      sistemas de cabinas SAN All-Flash y cabinas flash híbrido FAS.
    tags: all, hardware
  - title: Sistemas ASA r2
    icon: "./media/groups_line.png"
    url: https://docs.netapp.com/us-en/asa-r2/index.html
    summary: Instale su sistema ASA R2 y utilice ONTAP para gestionar sus datos.
    tags: all, hardware
  - title: ONTAP MetroCluster
    icon: "./media/metrocluster.png"
    url: https://docs.netapp.com/us-en/ontap-metrocluster/
    summary: Proteger su almacenamiento mediante clustering basado en cabinas con
      replicación síncrona para ofrecer una disponibilidad continua.
    tags: all, protection
  - title: Configuración de hosts SAN ONTAP
    icon: "./media/server.png"
    url: https://docs.netapp.com/us-en/ontap-sanhost/
    summary: Configure los hosts SAN ONTAP para los protocolos NVMe, iSCSI y FC.
    tags: all, management
  - title: Informes técnicos de ONTAP
    icon: "./media/icon-onprem.png"
    url: https://docs.netapp.com/us-en/ontap-technical-reports/index.html
    summary: Obtenga más información sobre la arquitectura ONTAP y cómo optimizar
      ONTAP en cargas de trabajo y entornos específicos.
    tags: all, management, protection
  - title: Comandos de la ONTAP
    icon: "./media/cli.png"
    url: https://docs.netapp.com/us-en/ontap-cli/
    summary: Obtenga información acerca de los comandos que tiene disponibles en la
      CLI de ONTAP.
    tags: all, management
  - title: Referencia de ONTAP EMS
    icon: "./media/cli.png"
    url: https://docs.netapp.com/us-en/ontap-ems-9141/
    summary: Obtenga información sobre los eventos del sistema de mensajería de eventos
      (EMS) en ONTAP.
    tags: all, management
  - title: Automatización de ONTAP
    icon: "./media/icon-api.png"
    url: https://docs.netapp.com/us-en/ontap-automation/index.html
    summary: Automatice la puesta en marcha y administración de sus sistemas de almacenamiento
      de ONTAP mediante la API DE REST de ONTAP y las tecnologías compatibles.
    tags: all, automation, management
  - title: Cloud Volumes ONTAP
    icon: "./media/icon-cvo.png"
    url: https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html
    summary: Instale una instancia virtual de ONTAP para lograr que el almacenamiento
      en cloud sea más asequible, inteligente, conforme a las normativas y seguro.
    tags: all, management, protection
  - title: ONTAP Select
    icon: "./media/server.png"
    url: https://docs.netapp.com/us-en/ontap-select/
    summary: Ponga en marcha ONTAP como dispositivo de almacenamiento definido por
      software en una variedad de servidores de hardware de consumo que ejecutan el
      hipervisor ESXi de VMware.
    tags: all, management, protection
  - title: Importación de LUN externa de ONTAP
    icon: "./media/transition-tools.png"
    url: https://docs.netapp.com/us-en/ontap-fli/
    summary: Migre las LUN de cabinas de terceros y sistemas 7-Mode al almacenamiento
      NetApp moderno.
    tags: all, migration
